---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=43200

- name: Install rsyslog
  package: name=rsyslog state=present

- name: Configure rsyslog
  template: src={{item.src}} dest={{item.dst}}
  with_items:
    - { 'src': 'templates/rsyslog.conf.j2', 'dst': '/etc/rsyslog.conf' }
    - { 'src': 'templates/nginx.conf.j2', 'dst': '/etc/rsyslog.d/nginx.conf' }
  notify:
    - restart rsyslog
